export {default as Header} from './Header/Header'
export {default as ABOUT} from './About//About'
export {default as Skills} from './Skills/Skills'
export {default as Footer} from './Footer/Footer'
export {default as Work} from './Work/Work'
export {default as Testimonial} from './Testimonial/Testimonial'